### ISSUE TITLE
Add other file type webpack loaders (html, txt, json, scss, ..)

### ISSUE THREAD

**Issue by sp00x** [McBen/IITCPluginKit#3]
Currently you can require("some.css") files 

It would be convenient to be able to load html/htm as separate files for UI 

Also would be good to include .json or .txt for other purposes, where you need to add additional data resources

(Aaaalso, a scss loader would be nice!)

HTML/JSON/TXT etc can be easily included using 'raw-loader' -  ` let settingsUi = require("./settings.html").default; `

( you can edit the webpack files in node_modules/iitcpluginkit manually but it keeps being rewritten all the time .. )

**Comment by McBen** [comment]
Note:
IPK uses postcss. The syntax is really similiar to sass:
```
@import 'buttons';

$IITC_YELOW: #ffce00; 

.myblock {
    .anotherblock {  
        color: $IITC_YELOW;
        background-color: color(red shade(20%)) 
    }
}
```
